services:
  - type: web
    name: telegram-bot-factory
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8560458596:AAGz2QlOIgVSt3RCYjG4U3eklOTw1HlS4_U"
        sync: false
      
      # حط مفتاح Groq API هنا - من console.groq.com
      - key: GROQ_API_KEY
        value: "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"
        sync: false